#!/bin/bash
read -p "Enter input:" val
echo "$val"|grep "^[0-9]*.[0-9]*$"

val="$?"

if [[ "$val" == 0 ]]
then
echo "It is a number."
exit
fi

echo "$letter"|grep "^[a-zA-Z]*$"
letter="$?"

if [[ "$letter" == 0 ]]
then
echo "It is a string."
exit
fi
